# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import main_desk as md

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 509)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame = QtGui.QFrame(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(45)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 7, 0, 1, 2)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 7, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.frame)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 7, 4, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.frame)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.frame)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.lcdNumber = QtGui.QLCDNumber(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMinimumSize(QtCore.QSize(30, 50))
        self.lcdNumber.setAutoFillBackground(True)
        self.lcdNumber.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout_2.addWidget(self.lcdNumber, 4, 1, 1, 1)
        self.listView = QtGui.QListView(self.frame)
        self.listView.setAutoFillBackground(True)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout_2.addWidget(self.listView, 1, 2, 6, 3)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_2.setSizePolicy(sizePolicy)
        self.lcdNumber_2.setAutoFillBackground(True)
        self.lcdNumber_2.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.gridLayout_2.addWidget(self.lcdNumber_2, 5, 0, 1, 2)
        self.gridLayout_3.addWidget(self.frame, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_25 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.gridLayout_4.addWidget(self.pushButton_25, 6, 0, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_4.addWidget(self.pushButton_15, 1, 2, 1, 1)
        self.pushButton_23 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.gridLayout_4.addWidget(self.pushButton_23, 5, 0, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_4.addWidget(self.pushButton_22, 3, 2, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_4.addWidget(self.pushButton_16, 2, 0, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_4.addWidget(self.pushButton_21, 6, 2, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_4.addWidget(self.pushButton_17, 2, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_4.addWidget(self.pushButton_6, 2, 3, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_4.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_4.addWidget(self.pushButton_9, 6, 3, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_4.addWidget(self.pushButton_12, 0, 0, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_4.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_4.addWidget(self.pushButton_19, 3, 0, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_4.addWidget(self.pushButton_10, 0, 2, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_4.addWidget(self.pushButton_7, 3, 3, 1, 1)
        self.pushButton_27 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.gridLayout_4.addWidget(self.pushButton_27, 5, 2, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_4.addWidget(self.pushButton_20, 3, 1, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_4.addWidget(self.pushButton_8, 5, 3, 1, 1)
        self.pushButton_26 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.gridLayout_4.addWidget(self.pushButton_26, 6, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_4.addWidget(self.pushButton_13, 1, 0, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_4.addWidget(self.pushButton_14, 1, 1, 1, 1)
        self.pushButton_24 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.gridLayout_4.addWidget(self.pushButton_24, 5, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_4.addWidget(self.pushButton_5, 1, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCadastro = QtGui.QMenu(self.menubar)
        self.menuCadastro.setObjectName(_fromUtf8("menuCadastro"))
        self.menuEstoque = QtGui.QMenu(self.menubar)
        self.menuEstoque.setObjectName(_fromUtf8("menuEstoque"))
        self.menuConsultar = QtGui.QMenu(self.menubar)
        self.menuConsultar.setObjectName(_fromUtf8("menuConsultar"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        self.menuRelat_rios = QtGui.QMenu(self.menubar)
        self.menuRelat_rios.setObjectName(_fromUtf8("menuRelat_rios"))
        self.menuRelat_rio_de_vendas = QtGui.QMenu(self.menuRelat_rios)
        self.menuRelat_rio_de_vendas.setObjectName(_fromUtf8("menuRelat_rio_de_vendas"))
        self.menuRelat_rio_de_estoque = QtGui.QMenu(self.menuRelat_rios)
        self.menuRelat_rio_de_estoque.setObjectName(_fromUtf8("menuRelat_rio_de_estoque"))
        self.menuAjuda_2 = QtGui.QMenu(self.menubar)
        self.menuAjuda_2.setObjectName(_fromUtf8("menuAjuda_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCadastrar_produto = QtGui.QAction(MainWindow)
        self.actionCadastrar_produto.setObjectName(_fromUtf8("actionCadastrar_produto"))
        self.actionCadastrar_item_card_pio = QtGui.QAction(MainWindow)
        self.actionCadastrar_item_card_pio.setObjectName(_fromUtf8("actionCadastrar_item_card_pio"))
        self.actionCadastrar_funcion_rio = QtGui.QAction(MainWindow)
        self.actionCadastrar_funcion_rio.setObjectName(_fromUtf8("actionCadastrar_funcion_rio"))
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.actionCadastrar_novo_item = QtGui.QAction(MainWindow)
        self.actionCadastrar_novo_item.setCheckable(False)
        self.actionCadastrar_novo_item.setChecked(False)
        self.actionCadastrar_novo_item.setObjectName(_fromUtf8("actionCadastrar_novo_item"))
        self.actionAtualizar_estoque = QtGui.QAction(MainWindow)
        self.actionAtualizar_estoque.setObjectName(_fromUtf8("actionAtualizar_estoque"))
        self.actionAtualizar_Estoque = QtGui.QAction(MainWindow)
        self.actionAtualizar_Estoque.setObjectName(_fromUtf8("actionAtualizar_Estoque"))
        self.actionSair_2 = QtGui.QAction(MainWindow)
        self.actionSair_2.setObjectName(_fromUtf8("actionSair_2"))
        self.actionConsultar_produto = QtGui.QAction(MainWindow)
        self.actionConsultar_produto.setObjectName(_fromUtf8("actionConsultar_produto"))
        self.actionConsultar_funcion_rio = QtGui.QAction(MainWindow)
        self.actionConsultar_funcion_rio.setObjectName(_fromUtf8("actionConsultar_funcion_rio"))
        self.actionConsultar_Estoque = QtGui.QAction(MainWindow)
        self.actionConsultar_Estoque.setObjectName(_fromUtf8("actionConsultar_Estoque"))
        self.actionSair_3 = QtGui.QAction(MainWindow)
        self.actionSair_3.setObjectName(_fromUtf8("actionSair_3"))
        self.actionSupore = QtGui.QAction(MainWindow)
        self.actionSupore.setObjectName(_fromUtf8("actionSupore"))
        self.actionSair_4 = QtGui.QAction(MainWindow)
        self.actionSair_4.setObjectName(_fromUtf8("actionSair_4"))
        self.actionSair_5 = QtGui.QAction(MainWindow)
        self.actionSair_5.setObjectName(_fromUtf8("actionSair_5"))
        self.actionVendas_por_per_odo = QtGui.QAction(MainWindow)
        self.actionVendas_por_per_odo.setObjectName(_fromUtf8("actionVendas_por_per_odo"))
        self.actionRelat_rio_por_per_odo = QtGui.QAction(MainWindow)
        self.actionRelat_rio_por_per_odo.setObjectName(_fromUtf8("actionRelat_rio_por_per_odo"))
        self.actionRelat_rio_por_produto = QtGui.QAction(MainWindow)
        self.actionRelat_rio_por_produto.setObjectName(_fromUtf8("actionRelat_rio_por_produto"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.menuCadastro.addAction(self.actionCadastrar_produto)
        self.menuCadastro.addAction(self.actionCadastrar_item_card_pio)
        self.menuCadastro.addAction(self.actionCadastrar_funcion_rio)
        self.menuCadastro.addSeparator()
        self.menuCadastro.addAction(self.actionSair)
        self.menuEstoque.addAction(self.actionCadastrar_novo_item)
        self.menuEstoque.addAction(self.actionAtualizar_estoque)
        self.menuEstoque.addAction(self.actionAtualizar_Estoque)
        self.menuEstoque.addSeparator()
        self.menuEstoque.addAction(self.actionSair_2)
        self.menuConsultar.addAction(self.actionConsultar_produto)
        self.menuConsultar.addAction(self.actionConsultar_funcion_rio)
        self.menuConsultar.addAction(self.actionConsultar_Estoque)
        self.menuConsultar.addSeparator()
        self.menuConsultar.addAction(self.actionSair_3)
        self.menuAjuda.addAction(self.actionSupore)
        self.menuAjuda.addSeparator()
        self.menuAjuda.addAction(self.actionSair_5)
        self.menuRelat_rio_de_vendas.addAction(self.actionVendas_por_per_odo)
        self.menuRelat_rio_de_estoque.addAction(self.actionRelat_rio_por_per_odo)
        self.menuRelat_rio_de_estoque.addAction(self.actionRelat_rio_por_produto)
        self.menuRelat_rio_de_estoque.addSeparator()
        self.menuRelat_rios.addAction(self.menuRelat_rio_de_vendas.menuAction())
        self.menuRelat_rios.addAction(self.menuRelat_rio_de_estoque.menuAction())
        self.menuRelat_rios.addSeparator()
        self.menuRelat_rios.addAction(self.actionSair_4)
        self.menuAjuda_2.addAction(self.actionSobre)
        self.menuAjuda_2.addSeparator()
        self.menubar.addAction(self.menuCadastro.menuAction())
        self.menubar.addAction(self.menuEstoque.menuAction())
        self.menubar.addAction(self.menuConsultar.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.menubar.addAction(self.menuRelat_rios.menuAction())
        self.menubar.addAction(self.menuAjuda_2.menuAction())
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_5.setText(_translate("MainWindow", "Volte Sempre !", None))
        self.pushButton.setText(_translate("MainWindow", "Cancelar Item", None))
        self.label.setText(_translate("MainWindow", "Item:", None))
        self.pushButton_2.setText(_translate("MainWindow", "Cancelar Venda", None))
        self.label_3.setText(_translate("MainWindow", "Descrição:", None))
        self.pushButton_3.setText(_translate("MainWindow", "Fechar", None))
        self.label_2.setText(_translate("MainWindow", "Quantidade:", None))
        self.label_4.setText(_translate("MainWindow", "Subtotal:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Caixa", None))
        self.pushButton_25.setText(_translate("MainWindow", "MESA 21", None))
        self.pushButton_15.setText(_translate("MainWindow", "MESA7", None))
        self.pushButton_23.setText(_translate("MainWindow", "MESA 17", None))
        self.pushButton_22.setText(_translate("MainWindow", "MESA 15", None))
        self.pushButton_16.setText(_translate("MainWindow", "MESA 9", None))
        self.pushButton_21.setText(_translate("MainWindow", "MESA 23", None))
        self.pushButton_17.setText(_translate("MainWindow", "MESA 10", None))
        self.pushButton_6.setText(_translate("MainWindow", "MESA 12", None))
        self.pushButton_11.setText(_translate("MainWindow", "MESA 2", None))
        self.pushButton_9.setText(_translate("MainWindow", "MESA 24", None))
        self.pushButton_12.setText(_translate("MainWindow", "MESA 1", None))
        self.pushButton_18.setText(_translate("MainWindow", "MESA 11", None))
        self.pushButton_19.setText(_translate("MainWindow", "MESA 13", None))
        self.pushButton_10.setText(_translate("MainWindow", "MESA 3", None))
        self.pushButton_7.setText(_translate("MainWindow", "MESA 16", None))
        self.pushButton_27.setText(_translate("MainWindow", "MESA 19", None))
        self.pushButton_20.setText(_translate("MainWindow", "MESA 14", None))
        self.pushButton_8.setText(_translate("MainWindow", "MESA 20", None))
        self.pushButton_26.setText(_translate("MainWindow", "MESA 22", None))
        self.pushButton_4.setText(_translate("MainWindow", "MESA 4", None))
        self.pushButton_13.setText(_translate("MainWindow", "MESA 5", None))
        self.pushButton_14.setText(_translate("MainWindow", "MESA 6", None))
        self.pushButton_24.setText(_translate("MainWindow", "MESA 18", None))
        self.pushButton_5.setText(_translate("MainWindow", "MESA 8", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Mesas", None))
        self.menuCadastro.setTitle(_translate("MainWindow", "Cadastro", None))
        self.menuEstoque.setTitle(_translate("MainWindow", "Estoque", None))
        self.menuConsultar.setTitle(_translate("MainWindow", "Consultar", None))
        self.menuAjuda.setTitle(_translate("MainWindow", "Financeiro", None))
        self.menuRelat_rios.setTitle(_translate("MainWindow", "Relatórios", None))
        self.menuRelat_rio_de_vendas.setTitle(_translate("MainWindow", "Relatório de vendas", None))
        self.menuRelat_rio_de_estoque.setTitle(_translate("MainWindow", "Relatório de estoque", None))
        self.menuAjuda_2.setTitle(_translate("MainWindow", "Ajuda", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionCadastrar_produto.setText(_translate("MainWindow", "Cadastrar produto", None))
        self.actionCadastrar_item_card_pio.setText(_translate("MainWindow", "Cadastrar item cardápio", None))
        self.actionCadastrar_funcion_rio.setText(_translate("MainWindow", "Cadastrar funcionário", None))
        self.actionSair.setText(_translate("MainWindow", "Sair ", None))
        self.actionCadastrar_novo_item.setText(_translate("MainWindow", "Cadastrar novo item", None))
        self.actionAtualizar_estoque.setText(_translate("MainWindow", "Excluir item", None))
        self.actionAtualizar_Estoque.setText(_translate("MainWindow", "Atualizar Estoque", None))
        self.actionSair_2.setText(_translate("MainWindow", "Sair", None))
        self.actionConsultar_produto.setText(_translate("MainWindow", "Consultar produto", None))
        self.actionConsultar_funcion_rio.setText(_translate("MainWindow", "Consultar funcionário", None))
        self.actionConsultar_Estoque.setText(_translate("MainWindow", "Consultar Estoque", None))
        self.actionSair_3.setText(_translate("MainWindow", "Sair", None))
        self.actionSupore.setText(_translate("MainWindow", "Movimento financeiro", None))
        self.actionSair_4.setText(_translate("MainWindow", "Sair", None))
        self.actionSair_5.setText(_translate("MainWindow", "Sair", None))
        self.actionVendas_por_per_odo.setText(_translate("MainWindow", "Vendas por período", None))
        self.actionRelat_rio_por_per_odo.setText(_translate("MainWindow", "Relatório por período", None))
        self.actionRelat_rio_por_produto.setText(_translate("MainWindow", "Relatório por produto", None))
        self.actionSobre.setText(_translate("MainWindow", "Sobre...", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
	ins = md.input_data()
	dele = del_data()
	opt = input("opcao:  1 insere 2 deleta :  ")

    if opt == 1:
        ins.data_estq()
    if opt == 2:
        dele.del_est()
	sys.exit(app.exec_())
##############
	

